# Parts of this file are based on:
#   url: https://github.com/al3x/sovereign/blob/a48a9941009cc1f18450d01cc7cf4f067ece3fae/roles/tarsnap/tasks/tarsnap.yml
#   contributors:  al3x jplock lvillani lukecyca jsravn bcachet alexdunae pdebruic
# The sovereign project source and this derivative work are licensed under the GNU General Public License v3.

- name: Install dependencies for Tarsnap
  apt: pkg={{ item }} state=installed
  with_items:
    - e2fslibs-dev
    - libssl-dev
    - zlib1g-dev
    - build-essential
    - python-setuptools

- name: Check if tarsnap {{ tarsnap_version }} is installed
  shell: tarsnap --version | grep {{ tarsnap_version }} --color=never
  register: tarnsap_installed
  changed_when: "tarnsap_installed.stderr != ''"
  ignore_errors: yes

- name: Download the current tarsnap code signing key
  when: tarnsap_installed|failed
  get_url:
    url=https://www.tarsnap.com/tarsnap-signing-key.asc
    dest=/root/tarsnap-signing-key.asc

- name: Add the tarsnap code signing key to your list of keys
  when: tarnsap_installed|failed
  command:
    gpg --import tarsnap-signing-key.asc
    chdir=/root/

- name: Download tarsnap SHA file
  when: tarnsap_installed|failed
  get_url:
    url="https://www.tarsnap.com/download/tarsnap-sigs-{{ tarsnap_version }}.asc"
    dest="/root/tarsnap-sigs-{{ tarsnap_version }}.asc"

- name: get the SHA256sum for this tarsnap release
  when: tarnsap_installed|failed
  shell: >
    gpgResult=`gpg --decrypt tarsnap-sigs-{{ tarsnap_version }}.asc 2>/dev/null`;
    echo ${gpgResult#*=};
  args:
    executable: /bin/bash
    chdir: /root
  register: tarsnap_sha

- name: Download Tarsnap source
  when: tarnsap_installed|failed
  get_url:
    url="https://www.tarsnap.com/download/tarsnap-autoconf-{{ tarsnap_version }}.tgz"
    dest="/root/tarsnap-autoconf-{{ tarsnap_version }}.tgz"
    sha256sum={{ tarsnap_sha.stdout_lines[0] }}

- name: Decompress Tarsnap source
  when: tarnsap_installed|failed
  command: tar xzf /root/tarsnap-autoconf-{{ tarsnap_version }}.tgz chdir=/root creates=/root/tarsnap-autoconf-{{ tarsnap_version }}/COPYING

- name: Configure Tarsnap for local build
  when: tarnsap_installed|failed
  command: ./configure chdir=/root/tarsnap-autoconf-{{ tarsnap_version }} creates=/root/tarsnap-autoconf-{{ tarsnap_version }}/Makefile

- name: Build and install Tarsnap
  when: tarnsap_installed|failed
  command: make all install clean chdir=/root/tarsnap-autoconf-{{ tarsnap_version }} creates=/usr/local/bin/tarsnap

- name: Create Tarsnap cache directory
  file: state=directory path={{ tarsnap_cache }}

- name: Install tarsnapper wrapper
  easy_install: name=tarsnapper

- name: Install tarsnapper configuration file
  copy: src={{ tarsnap_tarsnapper_conf }} dest=/root/tarsnapper.conf mode=644

- name: Install Tarsnap configuration file
  template: src=tarsnaprc.j2 dest=/root/.tarsnaprc mode=644

- name: Install tarsnapper backup script
  copy: src=tarsnap.sh dest=/root/tarsnap.sh mode=755

- name: Configure tarsnap logrotate
  copy: src=etc_logrotate_tarsnap dest=/etc/logrotate.d/tarsnap owner=root group=root mode=0644

- name: Install nightly Tarsnap-generations cronjob
  cron:
  args:
    name: "Tarsnap backup"
    job: "/root/tarsnap.sh > /dev/null"
    minute: "{{ tarsnap_cron_minute }}"
    hour: "{{ tarsnap_cron_hour }}"
    day: "{{ tarsnap_cron_day }}"
    month: "{{ tarsnap_cron_month }}"
